[package]
name = "andisbank-assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.0", features = ["rt", "rt-multi-thread", "macros"] }
reqwest = { version = "0.12.9", features = ["json", "multipart"] }
serde = "1.0.214"
serde_json = "1.0.132"
thiserror = "2.0.3"
